sudo: required

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GCP_KEY")
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

script:
  - ssh -o StrictHostKeyChecking=no cloud_user_p_f7e98f@35.239.116.27 "touch test"

deploy:
  provider: script
  script: 
  - ssh -o StrictHostKeyChecking=no cloud_user_p_f7e98f@35.238.116.27 "touch test"
  on:
    branch: master

