sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project playground-s-11-b929a5
  - gcloud config set compute/zone us-central1-a
script:
  - pwd
  - whoami
  - git commit -am 'test'

deploy:
  provider: script
  script: 
  - ssh -o StrictHostKeyChecking=no cloud_user_p_dfae2c@35.238.113.19 "touch test"
  on:
    branch: master

