sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project playground-s-11-b929a5
  - gcloud config set compute/zone us-central1-a
  - docker build --tag node-travis:v1 .
script:
  - pwd
  - touch test
  - whoami

deploy:
  provider: script
  script: 
  - pwd
  - whoami
  on:
    branch: master

